### ISSUE TITLE
Add image thumbnail feature

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#124]
Currently, we are loading the original images into lists, it is pretty slow and unnecessary, we need a thumbnail service to crop the image to show thumbnail.

Reference: https://github.com/Greenstand/treetracker-admin-client/blob/master/src/components/OptimizedImage.js

<img width="1440" alt="Screen Shot 2021-09-25 at 11 41 29 AM" src="https://user-images.githubusercontent.com/5744708/134756627-1a9bec71-e524-4935-a3ec-9e35bf1b97a3.png">

---
Some hints:
* Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

**Comment by jwgatt** [comment]
This one looks decent https://cloudinary.com/documentation/image_transformations

**Comment by dadiorchen** [comment]
@jwgatt great, I ever used that service, I mean cloudinary.com, it's good, our admin panel team is using this service: https://statically.io/ what do you think? Which one you prefer.

**Comment by VWRoli** [comment]
Are you working on this @jwgatt ? Because I have a working solution with https://statically.io/  and the admin client code.

**Comment by jwgatt** [comment]
I was just investigating to get myself up-to-date. If you have a working solution, go for it.
