### ISSUE TITLE
Browser throwing TypeError on deploy

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-wallet-web#135]
Browser throwing TypeError on deploy

**To Reproduce**
Run `npm start` from console

**Expected behavior**
 I expected the client to run locally on my machine.

**Desktop:**
Linux Ubuntu 20.04
Chromium 93.0 / Firefox 92.0

![image](https://user-images.githubusercontent.com/79326421/135922148-25d419e7-8334-4421-9c8f-beaff8714fa5.png)

I have found that if I remove `.split()` from line 24 in the above image, the app deploys. @dadiorchen What was the purpose of `.split()` in this context?

**Comment by dadiorchen** [comment]
@jwgatt we must convert the string "domain1,domain2,domain3" to array: ["domain1", "domain2", "domain3"], because that's the type leaflet needed for the option.

**Comment by dadiorchen** [comment]
@jwgatt is this still a valid bug?

**Comment by jwgatt** [comment]
> @jwgatt is this still a valid bug?
No, I think it was a local problem on my machine.
