### ISSUE TITLE
Map showing european country names in wrong language

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-wallet-web#137]
Map showing some European countries in French and Spanish instead of default English, at certain zoom levels. Curiously this only happens on the European continent, it doesn't happen elsewhere on the map as far as I can see.

**To Reproduce**
Deploy the app and zoom-in with mouse wheel towards Europe

**Expected behavior**
Country names should remain the same language, regardless of zoom level

**Desktop :**
Linux Ubuntu 20.04
Chromium 93.0 / Firefox 92.0

![zoomIssue](https://user-images.githubusercontent.com/79326421/136090641-d4db16ed-7af3-43f4-a93c-b036685f8f53.gif)

Loom link https://www.loom.com/share/1dc94401954b481588482016ef1d4f79?sharedAppSource=personal_library

**Comment by dadiorchen** [comment]
@jwgatt is this related to https://github.com/Greenstand/treetracker-web-map-client/issues/199

**Comment by jwgatt** [comment]
I'm not sure but I cannot reproduce this bug now so I will close this issue until further notice.
