### ISSUE TITLE
Refine the CSS of the wallet page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#163]
Currently, the wallet page is a little different from the UI design, we need someone who is familiar with CSS to refine the UI to match the design file.

Our UI design:

![image](https://user-images.githubusercontent.com/5744708/141937331-cffab14f-538b-4eb8-b32c-f899b05ef1c9.png)

our implementation.
<img width="358" alt="Screen Shot 2021-11-16 at 3 05 29 PM" src="https://user-images.githubusercontent.com/5744708/141937348-0b375e48-114f-42b2-90db-b6d6bf4e8514.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by VWRoli** [comment]
I will take a look at it, but mine does not look as bad as yours. Mostly just margin and padding issues
![Screenshot from 2021-11-16 16-25-17](https://user-images.githubusercontent.com/31432331/142014452-2b020c04-7e2b-4e4c-a59d-a70523188818.png)
.

**Comment by dadiorchen** [comment]
Thanks @VWRoli ! I'm wondering why yours and mine is different.

**Comment by VWRoli** [comment]
> Thanks @VWRoli ! I'm wondering why yours and mine is different.

That's a good question. I tried on different browsers and it looks the same (Brave, Chrome, Firefox).
