### ISSUE TITLE
The last timeline item shouldn't have a link line

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#172]
<img width="1434" alt="Screen Shot 2021-11-18 at 10 09 36 AM" src="https://user-images.githubusercontent.com/5744708/142338579-078ef599-15d5-432e-9e52-6c45fba19cd7.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by bedgarone** [comment]
Hi @dadiorchen, may I be added to the Slack community? brunoedgarero@gmail.com 
I would like to contribute and have already filled the join form.
Regards

**Comment by dadiorchen** [comment]
Thank you! yes, I will invite you!

**Comment by dadiorchen** [comment]
@bedgarone will you take this issue?
