### ISSUE TITLE
Install prettier

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#18]
And the rule to run it, Refer to https://github.com/Greenstand/treetracker-admin-client

**Comment by dadiorchen** [comment]
Requirements:
* When user commit code, must make sure the code is in a good format. It's a good chance to enable the prettier at the start of a project, to make sure the code is in good style/format

**Comment by VWRoli** [comment]
Hello! Worked on this and added a PR.
