### ISSUE TITLE
`npm run build` doesn't work

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#191]
1. clone the repo
2. npm ci (I didnt' use npm i, maybe this is the reason, I'm not sure)
3. npm run build

```
  10005 root@aliyun:~/treetracker-wallet-web# npm run build
  10006
  10007 > wallet-app@1.0.0 build
  10008 > GENERATE_SOURCEMAP=false react-scripts build
  10009
  10010 Creating an optimized production build...
  10011 Failed to compile.
  10012
  10013 Cannot read properties of undefined (reading 'includes')
  10014
  10015
  10016 root@aliyun:~/treetracker-wallet-web#
```

---
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@VWRoli seems there are some weird npm things going on currently ;(

@Siddhant-K-code this happens on your side right?

**Comment by dadiorchen** [comment]
@VWRoli why we need to upgrade to react 17?

**Comment by Siddhant-K-code** [comment]
Yeah, I was also curious that what is the need for this : [ `node-version >= 16` ](https://github.com/Greenstand/treetracker-wallet-web/blob/main/package.json#L76)

**Comment by VWRoli** [comment]
Not working on my side either with my original copy of the repo.

> @VWRoli why we need to upgrade to react 17?

We did not upgrade to 17, the project was initialized with 17.

**Comment by dadiorchen** [comment]
@VWRoli interesting, theoretically, mock server things should have an impact on this

Me too, I can run `npm start` but can not build, the embarrassing situation is that the command doesn't throw any error message when failing

**Comment by VWRoli** [comment]
Success
