### ISSUE TITLE
Change the app title to: Greenstand Wallet

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#205]
![image](https://user-images.githubusercontent.com/5744708/146295399-5927125a-ac66-4105-a9b8-f1edd90ccdda.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/28

**Comment by nitin094-hub** [comment]
Could you plz assign this to me?

**Comment by dadiorchen** [comment]
Hey, it's yours!

**Comment by arcadioramos** [comment]
If this wasn't solved yet can I work on it?

**Comment by dadiorchen** [comment]
@arcadioramos @nitin094-hub is already on it, take a look at these list, all these issues are open for everyone:
https://github.com/orgs/Greenstand/projects/26
https://github.com/orgs/Greenstand/projects/28
