### ISSUE TITLE
Refractor/remove legacy MaterialUI v4 code

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-wallet-web#207]
Cypress is throwing errors which i think are related to legacy materialui code such as makeStyles and useStyles etc.

![Screenshot from 2021-12-20 03-40-37](https://user-images.githubusercontent.com/79326421/146704285-c459eeff-0eaa-4ae5-9926-024c0a3f8fdd.png)

**Comment by jwgatt** [comment]
Done. [#202 ](https://github.com/Greenstand/treetracker-wallet-web/pull/202)

**Comment by VWRoli** [comment]
This is taken care of in #197
