### ISSUE TITLE
The token list

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#27]
![image](https://user-images.githubusercontent.com/5744708/130588256-5e58430a-a158-42c6-8d05-984345fc4ea3.png)

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/

**Comment by dadiorchen** [comment]
This should be an infinite list, when scrolling down to the bottom, the list should load the next page.
When there isn't any more data, should show: `no more data` at the bottom of the list.

**Comment by dadiorchen** [comment]
Please use mock data to build it.

**Comment by VWRoli** [comment]
Working on this one.

**Comment by dadiorchen** [comment]
@VWRoli, I found @YassinHussein did some work on this, please take a look, @YassinHussein some hints: you can comment on the issue that you are on, and when you post a PR, add workds like: "resolves #xxx" to link the PR to issue which is relevant.

**Comment by dadiorchen** [comment]
Oh, @YassinHussein I guess you didn't implement the infinite scroll down right? in the PR?

**Comment by YassinHussein** [comment]
> @VWRoli, I found @YassinHussein did some work on this, please take a look, @YassinHussein some hints: you can comment on the issue that you are on, and when you post a PR, add workds like: "resolves #xxx" to link the PR to issue which is relevant.

@dadiorchen @VWRoli  pardon me and thanks for the hints

**Comment by YassinHussein** [comment]
> Oh, @YassinHussein I guess you didn't implement the infinite scroll down right? in the PR?

yeah i didn't implement it yet, my idea was to create this as a single token component and implement  infinite scroll in a separate reusable  component

**Comment by VWRoli** [comment]
> @VWRoli, I found @YassinHussein did some work on this, please take a look, @YassinHussein some hints: you can comment on the issue that you are on, and when you post a PR, add workds like: "resolves #xxx" to link the PR to issue which is relevant.

Alright.
