### ISSUE TITLE
The UX/UI about the share function. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#30]
@rgesulfo Do you think that we need to design a share page/dialog for the share function? We have a simple one on the current web map, but we just build it with the default component in the lib we are using. It's not so pretty in my opnion.

<img width="1420" alt="Screen Shot 2021-08-25 at 11 54 52 AM" src="https://user-images.githubusercontent.com/5744708/130724260-64cdaad2-6dfa-4ade-aa78-4bf0c3420b08.png">

**Comment by dadiorchen** [comment]
You can try the current share button when you zoom in on treetracker.org and clicking a tree.

**Comment by rgesulfo** [comment]
Hi @dadiorchen, if you are up for it we can definitely try something a bit different. Here is what I'd do: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand-Wallet?node-id=1007%3A1186
What do you think? :)
In any case, this would only be for desktop as mobile leverages the native OS sharing interface right?
