### ISSUE TITLE
The tree/capture detail page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#31]
Create page + component for the tree/capture detail page, could use mock/fake data.

![image](https://user-images.githubusercontent.com/5744708/130724721-3c3e1f91-2623-45a0-b9ba-983780105025.png)

**Comment by dadiorchen** [comment]
The spec of API: https://github.com/Greenstand/treetracker-wallet-web/issues/29

Prerequisites: https://github.com/Greenstand/treetracker-wallet-web/issues/36 https://github.com/Greenstand/treetracker-wallet-web/issues/35

------
Some hint:
* How to mock the API: https://github.com/Greenstand/treetracker-wallet-web#how-to-mock-the-api

**Comment by dadiorchen** [comment]
https://www.loom.com/share/208a7948f64f43c5a2a09a675d0a5f01

**Comment by YassinHussein** [comment]
working on this
