### ISSUE TITLE
History transaction component.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#32]
Could use mock/fake data to present the component.

![image](https://user-images.githubusercontent.com/5744708/130724885-85094029-8274-4f93-a66d-647c52e78f16.png)

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/

**Comment by dadiorchen** [comment]
At this stage, please just consider a single page, without pagination.

**Comment by YassinHussein** [comment]
Working on this
