### ISSUE TITLE
Caution component. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#33]
![image](https://user-images.githubusercontent.com/5744708/130734278-a03dd114-dccd-40b3-80b1-64c4f67e769a.png)

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/

**Comment by monjurkhuda** [comment]
I would like to work on this component. Please add me to slack (email: kiatbrooklyn@gmail.com)
