### ISSUE TITLE
MatierialUI template/theme

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#34]
To define the them:
  * Colors
  * Fonts
  * Spacing.
  * Corner style.
  * And so on.
To bring the most convenience for the detailed pages when coding, avoid replicated troublesome style definition in the detailed code file.

**Comment by dadiorchen** [comment]
A reference:
https://github.com/Greenstand/treetracker-admin-client/blob/master/src/components/common/theme.js

**Comment by dadiorchen** [comment]
https://www.loom.com/share/4f97e682759b455f84c7e87f9bcdeb96

**Comment by dadiorchen** [comment]
Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71

**Comment by VWRoli** [comment]
Just noticed this issue, which is exactly what I wanted to ask, if we will have a theme. I will work on this before #27 the token list.
