### ISSUE TITLE
The detail page component.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#38]
Please note, this task is just about the frame of the page (the back button, and drawer) do not include the content in it.
![image](https://user-images.githubusercontent.com/5744708/130737456-7f409afb-c9ab-4681-bc40-c4a7c061fd17.png)

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/

**Comment by dadiorchen** [comment]
Being aware the area on the top should be transparent.

**Comment by dadiorchen** [comment]
https://www.loom.com/share/972fb2daaa5046bfb40d8d8389b56fdc

**Comment by dadiorchen** [comment]
Prerequisites: #36

**Comment by CalDev98** [comment]
I'll work on it
