### ISSUE TITLE
Button component. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#39]
Create a reusable button as a common component. 
![image](https://user-images.githubusercontent.com/5744708/130737778-e2ff806b-624a-43d7-8b11-68f22b7f83ef.png)

**Comment by dadiorchen** [comment]
Visit the slack channel for UI details.

**Comment by dadiorchen** [comment]
@shreyaansjain is this you in slack? I have invited you:
![image](https://user-images.githubusercontent.com/5744708/131203011-0c2e322b-998c-406c-99e1-6c483858326e.png)

**Comment by shreyaansjain** [comment]
Its not me i joined today and have given my intro 
Now as i have joined slack can you tell what i have to do
it will be really helpful
Thank You
