### ISSUE TITLE
Share component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#47]
The UI design: https://github.com/Greenstand/treetracker-wallet-web/issues/30
![image](https://user-images.githubusercontent.com/5744708/130886134-84b024f5-ff65-4e43-ae7e-f36ecb1e1c98.png)

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/

**Comment by dorukucak** [comment]
I am working on this.

**Comment by dadiorchen** [comment]
Finished
