### ISSUE TITLE
Share wallet function

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#49]
To share the wallet, (the share button on the wallet + token list page)
Please check the design details in the channel, and refer to the current share feature in the web map client. https://github.com/Greenstand/treetracker-web-map-client

<img width="1440" alt="Screen Shot 2021-09-04 at 11 21 57 AM" src="https://user-images.githubusercontent.com/5744708/132080844-134ba6fa-e9f2-4c22-932d-da1eda78a54b.png">

<img width="1440" alt="Screen Shot 2021-09-04 at 11 23 26 AM" src="https://user-images.githubusercontent.com/5744708/132080861-dd0aaab6-13cb-4a6d-a54c-539b9d72b54a.png">

**Comment by dadiorchen** [comment]
https://www.loom.com/share/494cfea894044e589e5f778bc7e3ecc6

**Comment by CalDev98** [comment]
I'll work on it
