### ISSUE TITLE
Remove the radius at the bottom.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#56]
Set the drawer radius but need to remove it at the bottom of the drawer.
<img width="910" alt="Screen Shot 2021-08-27 at 4 39 12 PM" src="https://user-images.githubusercontent.com/5744708/131099025-e2c0b445-6613-4ebd-997b-64d119e54fab.png">

**Comment by CalDev98** [comment]
I'll work on it
