### ISSUE TITLE
Readme about husky/eslint/prettier

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#68]
Add guide into readme for husky/eslint/prettier

**Comment by dadiorchen** [comment]
@VWRoli could you please give some guidance in the readme about these tools you installed?

**Comment by VWRoli** [comment]
Sure, but I'm going to need some more details. What were you thinking exactly? Not sure what should I write about them. The readme already contains information about Code style guide*.

Which has some typos in the eslint section.

**Comment by dadiorchen** [comment]
I think we should remove the code style guide, it might be a conflict with the current situation, actually it from the template.
I think we just need to let people know what we are using, and the commands and some explanation, and troubleshooting, and external link I guess some people will get stuck if they violated the husky commit message format rule, right?

**Comment by VWRoli** [comment]
@dadiorchen  Added a PR as a kind of a first draft. Check it and see if I should add, change or remove some things. 
I think we should also specify what the linting rules will be. Maybe install [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react)?

Also there is no husky commit message format rule. Right now husky only has a pre-commit hook for prettier and thats it.
