### ISSUE TITLE
Build component of token increasement graph

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#74]
Using library https://www.chartjs.org/ to build a graph component, please use static data to mock the graph (I mean we just need to draw the component following the UI design)

<img width="1440" alt="Screen Shot 2021-09-04 at 10 47 40 AM" src="https://user-images.githubusercontent.com/5744708/132080041-df5e2c68-e336-44ef-bb53-0a4fdbfd56aa.png">

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/

**Comment by dadiorchen** [comment]
API spec: #77

**Comment by YassinHussein** [comment]
work on it

**Comment by dadiorchen** [comment]
@YassinHussein which library will you use? I just read materialUI's document, they are supporting chart now: https://mui.com/x/

**Comment by YassinHussein** [comment]
I was going to use this library https://recharts.org, the chart component on MUI-x is not ready yet

**Comment by YassinHussein** [comment]
@dadiorchen what do you suggest

**Comment by dadiorchen** [comment]
That's fine, recharts is good

**Comment by dadiorchen** [comment]
Seems Chart.js is more popular and battle field checked, https://stackshare.io/stackups/js-chart-vs-recharts 
here is a react wrapper of it: react-chartjs-2

**Comment by YassinHussein** [comment]
@dadiorchen  ok great,  I will use chart.js
