### ISSUE TITLE
Share single tree function

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#76]
The prerequrites of this issue is #49 
<img width="1440" alt="Screen Shot 2021-09-04 at 11 20 11 AM" src="https://user-images.githubusercontent.com/5744708/132080811-d4d95a12-5799-406b-8daa-0b6f826e013d.png">

The only difference between this issue and #49  I guess is just the URL/link, so we definitely should think about reusing that code.

**Comment by VWRoli** [comment]
Working on this one
