### ISSUE TITLE
The impact tab

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#78]
This feature:
<img width="1440" alt="Screen Shot 2021-09-04 at 11 37 40 AM" src="https://user-images.githubusercontent.com/5744708/132081220-14dafb0b-2160-41b5-a43f-3dab5f47028e.png">

Note: don't implement the second graph, the `impact` line graph. 

The prerequisites of this feature, is some component, like the statistic graph, and others, they are tasks in other issues.

**Comment by dadiorchen** [comment]
The api spec: #77

**Comment by dadiorchen** [comment]
https://loom.com/share/871d9bc8e67947159f8bb06a5f258446

**Comment by VWRoli** [comment]
I would use a skeleton loading instead of the spinner. I think that would look better and more modern.
