### ISSUE TITLE
Remove the zoom in/out control panel on the map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#93]
cuz on the mobile app map we don't need it.
<img width="379" alt="Screen Shot 2021-09-07 at 9 57 26 AM" src="https://user-images.githubusercontent.com/5744708/132272651-1fff0e10-c2b9-4a14-918b-1d9c23b85c16.png">

**Comment by dadiorchen** [comment]
The map component is in another repository, so we need to folk and change that one too. https://github.com/Greenstand/treetracker-web-map-client

**Comment by jwgatt** [comment]
I'll work on this.

**Comment by jwgatt** [comment]
I have tried adding `zoomControl: false,` to the `mapOptions` in node_modules/client/src/models/Map.js, which is what the official leaflet docs suggest, but the zoom control is still visible. Another option would be to use this code; `map.removeControl(map.zoomControl);` but i'm still looking for the correct place to use it.

**Comment by dadiorchen** [comment]
Some clues:
* we are re-use Map class in treetracker-web-map-client, so if we want to change the behavior of the map, we need to change code in that repo.
* The Map class wrap the leaflet inside, so I guess the work is to open more settings for user on the Map.js, I prefer to translate the settings of Map's to leaflet's, let's make the user of Map zero knowledge of the implementation.

**Comment by dadiorchen** [comment]
https://github.com/Greenstand/treetracker-web-map-client/blob/web-map-site/src/models/Map.js

**Comment by jwgatt** [comment]
On it

**Comment by jwgatt** [comment]
Done [#172](https://github.com/Greenstand/treetracker-web-map-client/pull/172)
