### ISSUE TITLE
The group list card.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#96]
A single group list item component:
<img width="1440" alt="Screen Shot 2021-09-08 at 9 55 32 AM" src="https://user-images.githubusercontent.com/5744708/132433736-3689470e-38c2-447d-9ed5-831113c0da36.png">

-----------
Some hints for building components:
* Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
* A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.

**Comment by pvdo** [comment]
On it!

**Comment by jwgatt** [comment]
@pvdo Are you still working on this? Perhaps we could work together.

**Comment by pvdo** [comment]
Hey @jwgatt!
Actually, I have almost finished. I am just cleaning up the code.
Thanks for offering though.

**Comment by dadiorchen** [comment]
Thank you, guys! All the things are pushing forward, our two designers also are working on new features on these apps. @jwgatt I guess the guy on this issue is getting stalled, could you please take it: https://github.com/Greenstand/treetracker-wallet-web/issues/75
