### ISSUE TITLE
Make the default page desktop compatible.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-web#98]
The /wallets/[wallet name] page now is working correctly on the mobile device, now need to make it compatible with the desktop screen size, the design:

<img width="1440" alt="Screen Shot 2021-09-08 at 11 48 15 AM" src="https://user-images.githubusercontent.com/5744708/132443435-17e19bee-4bab-4a06-8499-ecb6a52f9be3.png">

**Comment by dadiorchen** [comment]
I guess the issue needs some advanced features of MatieralUI, like the Grid with xs/ms/... parameter, and some condition rendering according to the screen size. 

Or any other ideas/suggestions are welcome, feel free to discuss them here.

**Comment by VWRoli** [comment]
Is there a specific reason why the tab component have a different style on desktop? Or is it just an accident in the design? @dadiorchen

**Comment by dadiorchen** [comment]
Sorry for the confusion, the tab with a green background, is the correct version, this underscore-line style is wrong.

**Comment by dadiorchen** [comment]
@VWRoli will you take this one? If true, what's your idea on it?

**Comment by VWRoli** [comment]
> @VWRoli will you take this one? If true, what's your idea on it?

Yes, I will give it a try. 
I was thinking I use a state variable to check the screen width. Change the drawers anchor from bottom to left.
Make the drawer "sticky" (not swipable), as we will have enough map space for the user.
Let me know what you think.

**Comment by dadiorchen** [comment]
My main focus is how to implement these two versions, I mean both mobile and desktop, there are two choices: 
* A suite of components compatible with both.
* Tow suite of components implement them separately. 
What's your preference?
How about arranging a quick meeting? Or you can catch me when I'm online at any time, my timetable is pretty flexible.

**Comment by dadiorchen** [comment]
When I say implement them separately, mainly, I guess it's about the page frame, we still are able to reuse common/small components in it.

**Comment by YassinHussein** [comment]
@VWRoli I didn't know you  are working on this issue until I added a PL, sorry for that bro

**Comment by dadiorchen** [comment]
@YassinHussein please hold on, let's discuss and think it over, we make some big decision on how to implement it, the desktop design is in progress, we might be considering making the desktop version totally different with mobile one, because we can utilize bigger space on desktop to display more stuff, like this:
![image](https://user-images.githubusercontent.com/5744708/133949996-e4a4dbe4-123a-46cb-b07e-4b760c8305f9.png)

**Comment by VWRoli** [comment]
> @YassinHussein please hold on, let's discuss and think it over, we make some big decision on how to implement it, the desktop design is in progress, we might be considering making the desktop version totally different with mobile one, because we can utilize bigger space on desktop to display more stuff, like this:
> ![image](https://user-images.githubusercontent.com/5744708/133949996-e4a4dbe4-123a-46cb-b07e-4b760c8305f9.png)

If that's the case than I would go for a different page frame. This is much more complex than the mobile version, so using one suit of components would be difficult and inconvenient.

**Comment by YassinHussein** [comment]
> @YassinHussein please hold on, let's discuss and think it over, we make some big decision on how to implement it, the desktop design is in progress, we might be considering making the desktop version totally different with mobile one, because we can utilize bigger space on desktop to display more stuff, like this:
> ![image](https://user-images.githubusercontent.com/5744708/133949996-e4a4dbe4-123a-46cb-b07e-4b760c8305f9.png)

Ok, that is great

**Comment by YassinHussein** [comment]
> > @YassinHussein please hold on, let's discuss and think it over, we make some big decision on how to implement it, the desktop design is in progress, we might be considering making the desktop version totally different with mobile one, because we can utilize bigger space on desktop to display more stuff, like this:
> > ![image](https://user-images.githubusercontent.com/5744708/133949996-e4a4dbe4-123a-46cb-b07e-4b760c8305f9.png)
> 
> If that's the case than I would go for a different page frame. This is much more complex than the mobile version, so using one suit of components would be difficult and inconvenient.

I agree with you
